[2024-08-18T10:13:28.530+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-18T10:13:28.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_v1.convert_task manual__2024-08-18T10:13:17.215698+00:00 [queued]>
[2024-08-18T10:13:28.591+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_v1.convert_task manual__2024-08-18T10:13:17.215698+00:00 [queued]>
[2024-08-18T10:13:28.592+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-08-18T10:13:28.640+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): convert_task> on 2024-08-18 10:13:17.215698+00:00
[2024-08-18T10:13:28.672+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_v1', 'convert_task', 'manual__2024-08-18T10:13:17.215698+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_python.py', '--cfg-path', '/tmp/tmppej251fv']
[2024-08-18T10:13:28.686+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask convert_task
[2024-08-18T10:13:28.718+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=248) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-18T10:13:28.720+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2024-08-18T10:13:29.185+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_v1.convert_task manual__2024-08-18T10:13:17.215698+00:00 [running]> on host 481ee775c62e
[2024-08-18T10:13:30.660+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuclee' AIRFLOW_CTX_DAG_ID='data_pipeline_v1' AIRFLOW_CTX_TASK_ID='convert_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T10:13:17.215698+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-18T10:13:17.215698+00:00'
[2024-08-18T10:13:30.662+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-18T10:13:30.760+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_python.py:42 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-08-18T10:13:30.761+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-18T10:13:30.763+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_python.py", line 42, in convert_and_compress_data
    df = pd.read_json(input_file, lines=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 804, in read_json
    return json_reader.read()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 1012, in read
    obj = self._get_object_parser(self._combine_lines(data_lines))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 1040, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 1173, in parse
    self._parse()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 1366, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected object or value
[2024-08-18T10:13:30.813+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_v1, task_id=convert_task, run_id=manual__2024-08-18T10:13:17.215698+00:00, execution_date=20240818T101317, start_date=20240818T101328, end_date=20240818T101330
[2024-08-18T10:13:30.912+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task convert_task (Expected object or value; 265)
[2024-08-18T10:13:30.958+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-18T10:13:31.006+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-18T10:13:31.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
